using System.Net;
using Hoardr.Core.Notifications;
using Hoardr.Core.Workers;
using Hoardr.Tests.Support;

namespace Hoardr.Tests;

public class NtfyServiceTests
{
    [Fact]
    public void Topic_Is_Autogenerated_On_Migrate()
    {
        using var db = new TestDatabase();
        var ntfy = new NtfyService(db.Db, new HttpClient(new RecordingHandler()));

        var topic = ntfy.GetConfig().Topic;

        Assert.StartsWith("hoardr_", topic);
        Assert.Equal("hoardr_".Length + 6, topic.Length);
    }

    [Fact]
    public void Config_Roundtrips()
    {
        using var db = new TestDatabase();
        var ntfy = new NtfyService(db.Db, new HttpClient(new RecordingHandler()));

        ntfy.SaveConfig(new NtfyConfig { Enabled = true, Server = "https://ntfy.example", Topic = "hoardr", Token = "tok", ThresholdPercent = 75 });

        var cfg = ntfy.GetConfig();
        Assert.True(cfg.Enabled);
        Assert.Equal("https://ntfy.example", cfg.Server);
        Assert.Equal("hoardr", cfg.Topic);
        Assert.Equal(75, cfg.ThresholdPercent);
    }

    [Fact]
    public async Task Send_Does_Nothing_When_Disabled()
    {
        using var db = new TestDatabase();
        var handler = new RecordingHandler();
        var ntfy = new NtfyService(db.Db, new HttpClient(handler));

        Assert.False(await ntfy.SendAsync("t", "m"));
        Assert.Empty(handler.Requests);
    }

    [Fact]
    public async Task Send_Posts_To_Topic_With_Headers()
    {
        using var db = new TestDatabase();
        var handler = new RecordingHandler();
        var ntfy = new NtfyService(db.Db, new HttpClient(handler));
        ntfy.SaveConfig(new NtfyConfig { Enabled = true, Server = "https://ntfy.example/", Topic = "hoardr", Token = "tok" });

        var ok = await ntfy.SendAsync("Title", "Body", "high", "warning");

        Assert.True(ok);
        var req = Assert.Single(handler.Requests);
        Assert.Equal("https://ntfy.example/hoardr", req.RequestUri!.ToString());
        Assert.Equal("Title", req.Headers.GetValues("Title").Single());
        Assert.Equal("high", req.Headers.GetValues("Priority").Single());
        Assert.Equal("Bearer tok", req.Headers.GetValues("Authorization").Single());
        Assert.Equal("Body", handler.Bodies.Single());
    }

    [Fact]
    public async Task Send_Returns_False_On_Http_Error()
    {
        using var db = new TestDatabase();
        var ntfy = new NtfyService(db.Db, new HttpClient(new RecordingHandler(HttpStatusCode.InternalServerError)));
        ntfy.SaveConfig(new NtfyConfig { Enabled = true, Server = "https://n", Topic = "t" });

        Assert.False(await ntfy.SendAsync("t", "m"));
    }
}

public class DiskSpaceMonitorTests
{
    private static (NtfyService ntfy, RecordingHandler handler) Ntfy(TestDatabase db, int threshold)
    {
        var handler = new RecordingHandler();
        var ntfy = new NtfyService(db.Db, new HttpClient(handler));
        ntfy.SaveConfig(new NtfyConfig { Enabled = true, Server = "https://n", Topic = "t", ThresholdPercent = threshold });
        return (ntfy, handler);
    }

    [Fact]
    public async Task Alerts_Once_Then_Respects_Cooldown_And_Recovery()
    {
        using var db = new TestDatabase();
        var (ntfy, handler) = Ntfy(db, threshold: 80);
        var clock = FakeClock.At("2026-05-24 10:00:00");

        var usage = new DiskUsage(1000, 100); // 90% used
        var monitor = new DiskSpaceMonitor(ntfy, () => usage, clock) { ReAlertCooldown = TimeSpan.FromHours(6) };

        Assert.True(await monitor.RunOnceAsync());      // first alert
        Assert.Single(handler.Requests);

        Assert.False(await monitor.RunOnceAsync());      // cooldown
        Assert.Single(handler.Requests);

        clock.Advance(TimeSpan.FromHours(7));
        Assert.True(await monitor.RunOnceAsync());        // cooldown elapsed
        Assert.Equal(2, handler.Requests.Count);
    }

    [Fact]
    public async Task No_Alert_Below_Threshold()
    {
        using var db = new TestDatabase();
        var (ntfy, handler) = Ntfy(db, threshold: 80);
        var usage = new DiskUsage(1000, 500); // 50% used
        var monitor = new DiskSpaceMonitor(ntfy, () => usage, FakeClock.At("2026-05-24 10:00:00"));

        Assert.False(await monitor.RunOnceAsync());
        Assert.Empty(handler.Requests);
    }

    [Fact]
    public async Task No_Alert_When_Disabled()
    {
        using var db = new TestDatabase();
        var ntfy = new NtfyService(db.Db, new HttpClient(new RecordingHandler()));
        ntfy.SaveConfig(new NtfyConfig { Enabled = false, Server = "https://n", Topic = "t", ThresholdPercent = 80 });
        var monitor = new DiskSpaceMonitor(ntfy, () => new DiskUsage(1000, 10), FakeClock.At("2026-05-24 10:00:00"));

        Assert.False(await monitor.RunOnceAsync());
    }
}
